name: Init

on:
    workflow_call:
        inputs:
            push-to-registry:
                description: 'Push image to ghcr.io registry'
                required: false
                type: boolean
                default: false

env:
    # Disable uploading docker image builds as artifacts
    DOCKER_BUILD_RECORD_UPLOAD: false

jobs:
    init:
        runs-on: ubuntu-24.04
        name: Init - ${{ matrix.image.name }}
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Registry
              if: ${{ inputs.push-to-registry }}
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Task
              uses: go-task/setup-task@v1

            - name: Build and cache Docker image - ${{ matrix.image.name }}
              uses: docker/build-push-action@v6
              env:
                  IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}
              with:
                  push: ${{ inputs.push-to-registry }}
                  load: ${{ !inputs.push-to-registry }}
                  context: .
                  file: ./Dockerfile
                  target: dev
                  tags: ${{ env.IMAGE }}:ci-${{ github.sha }}
                  cache-from: ${{ inputs.push-to-registry && format('type=registry,ref={0}:cache', env.IMAGE) || 'type=gha' }}
                  cache-to: ${{ inputs.push-to-registry && format('type=registry,ref={0}:cache,mode=max', env.IMAGE) || 'type=gha,mode=max' }}
