name: Merge Automation

on:
    pull_request:
        types: [closed]
        branches:
            - develop

jobs:
    delete-branch:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-24.04
        permissions:
            contents: write
        steps:
            - name: Delete merged branch
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh api \
                    --method DELETE \
                    -H "Accept: application/vnd.github+json" \
                    /repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}

    retrigger-open-prs:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-24.04
        permissions:
        pull-requests: write
        steps:
        - name: Retrigger CI for open PRs (safe)
          env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              REPO: ${{ github.repository }}
          run: |
            prs=$(gh pr list \
                --repo "$REPO" \
                --base develop \
                --state open \
                --json number \
                -q '.[].number')

            for pr in $prs; do
                echo "Trigger synchronize on PR #$pr"

                gh api \
                -X PATCH \
                /repos/$REPO/pulls/$pr \
                -f title="$(gh pr view $pr --repo $REPO --json title -q .title)"
            done
